version: "3"

tasks:
  diff:
    cmds:
      - helmfile diff --kube-context {{.K8S_CONTEXT}}
    requires:
      vars:
        - K8S_CONTEXT

  apply:
    cmds:
      - helmfile apply --kube-context {{.K8S_CONTEXT}}
    requires:
      vars:
        - K8S_CONTEXT

  lint:
    cmds:
      - helmfile lint --kube-context {{.K8S_CONTEXT}}
    requires:
      vars:
        - K8S_CONTEXT
