{{ $domain := .Values.domain | required ".Values.domain is required." }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: grafana-security-middleware
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: "Host(`grafana.{{ $domain }}`)"
      services:
        - name: grafana
          port: 3000
      middlewares:
      - name: grafana-security-middleware
  tls:
    certResolver: letsencrypt

